default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: adc2024_vspyshka_development

test:
  <<: *default
  database: adc2024_vspyshka_test

production:
  <<: *default
  database: adc2024_vspyshka_production

  # username: <%= ENV['PG_USERNAME'] %>
  # password: <%= ENV['PG_PASSWORD'] %>
  # host:     <%= ENV['PG_HOST'] %>
  # port:     <%= ENV['PG_PORT'] %>
